# Generated by Django 3.2.9 on 2021-12-09 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_alter_customer_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='table_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='table_booked', to='reservations.tables'),
        ),
    ]
