# Generated by Django 3.2.9 on 2022-01-18 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_alter_reservation_requested_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='customer_name',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='table_id',
            new_name='table',
        ),
    ]
