# Generated by Django 3.2.9 on 2021-12-10 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_auto_20211210_0719'),
    ]

    operations = [
        migrations.AddField(
            model_name='tables',
            name='table_name',
            field=models.CharField(default='New table', max_length=10),
        ),
    ]
