# Generated by Django 3.2.9 on 2021-12-10 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_tables_table_name'),
    ]

    operations = [
       
        migrations.RenameModel(
            old_name='Reservations',
            new_name='Reservation',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='table_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='table_booked', to='reservations.tables'),
        ),
    ]
