# Generated by Django 3.2.9 on 2021-12-10 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_auto_20211210_0740'),
    ]

    operations = [
    ]
