# Generated by Django 3.2.9 on 2021-12-10 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_auto_20211210_0743'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tables',
            new_name='Table',
        ),

        
    ]
