# Generated by Django 3.2.9 on 2021-12-10 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0008_rename_table_tables'),
    ]

