# Generated by Django 3.2.9 on 2021-12-10 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0009_auto_20211210_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[(0, 'pending'), (1, 'confirmed')], default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='table',
            name='table_name',
            field=models.CharField(default='New table', max_length=10, unique=True),
        ),
    ]
