# Generated by Django 3.2.9 on 2021-12-12 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0010_auto_20211210_0756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='customer_id',
        ),
    ]
