# Generated by Django 3.2.9 on 2021-12-19 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0020_revert_email_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='customer_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='reservations.customer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
