# Generated by Django 3.2.9 on 2021-12-07 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_auto_20211207_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditems',
            name='allergens',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
