# Generated by Django 3.2.9 on 2021-12-07 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0003_alter_fooditems_allergens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinkitems',
            name='allergens',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
