# Generated by Django 3.2.9 on 2022-01-07 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0005_drinkitems_dietary'),
    ]

    operations = [
        migrations.AddField(
            model_name='drinkitems',
            name='price_link',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='fooditems',
            name='price_link',
            field=models.FloatField(null=True),
        ),
    ]
