# Generated by Django 3.2.9 on 2022-01-07 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0006_auto_20220107_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinkitems',
            name='price_link',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fooditems',
            name='price_link',
            field=models.FloatField(default='1'),
            preserve_default=False,
        ),
    ]
