# Generated by Django 3.2.9 on 2022-01-07 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0007_auto_20220107_0910'),
    ]

    operations = [
        migrations.RemoveField(
        model_name='DrinkItems',
        name='price',
    ),
    migrations.RenameField(
        model_name='DrinkItems',
        old_name='price_link',
        new_name='price',
    ),
       migrations.RemoveField(
        model_name='FoodItems',
        name='price',
    ),
    migrations.RenameField(
        model_name='FoodItems',
        old_name='price_link',
        new_name='price',
    ),
    ]
